baseURL = "https://stolpersteine-gangelt.de/"
languageCode = "de-DE"
DefaultContentLanguage = "de"
title = "Stolpersteine Gangelt"
theme = ["stolpersteine"]
# disableKinds = ["RSS"]
footnoteReturnLinkContents = "â†©"
# sectionPagesMenu = "main"
pluralizelisttitles = "false"
[params]
  debug = false
[taxonomies]
  category = "categories"
  tag = "tags"
[blackfriday]
  plainIDAnchors = false